local grp = {
    ["dynSpawnTemplate"] = false,
    ["modulation"] = 0,
    ["tasks"] = {},
    ["radioSet"] = false,
    ["task"] = "Nothing",
    ["uncontrolled"] = false,
    ["taskSelected"] = true,
    ["groupId"] = 1,
    ["hidden"] = false,
    ["units"] = {
        [1] = {
            ["alt"] = 10000,
            ["alt_type"] = "BARO",
            ["livery_id"] = "default",
            ["skill"] = "Player",
            ["speed"] = 219.44444444444,
            ["AddPropAircraft"] = {
                ["HelmetMountedDevice"] = 1,
                ["VoiceCallsignLabel"] = "ED",
                ["STN_L16"] = "00201",
                ["LAU3ROF"] = 0,
                ["VoiceCallsignNumber"] = "11",
            },
            ["type"] = "F-16C_50",
            ["unitId"] = 1,
            ["psi"] = -0,
            ["onboard_num"] = "010",
            ["y"] = 636026.54801183,
            ["x"] = -317984.7842086,
            ["name"] = "p1",
            ["payload"] = {
                ["pylons"] = {},
                ["fuel"] = 3249,
                ["flare"] = 60,
                ["ammo_type"] = 5,
                ["chaff"] = 60,
                ["gun"] = 100,
            },
            ["heading"] = 0,
        },
    },
    ["y"] = 636026.54801183,
    ["x"] = -317984.7842086,
    ["name"] = "g1",
    ["communication"] = true,
    ["start_time"] = 0,
    ["uncontrollable"] = false,
    ["frequency"] = 305,
}

return coalition.addGroup(country.id.USA, Group.Category.AIRPLANE, grp)