---------------------------------------------------------------------------
--- clickabledata.lua element definitions
---
--- runs in device env (see device-stubs.lua)
--- see also: Scripts\Aircrafts\_Common\Cockpit\clickable_common.lua
---------------------------------------------------------------------------

--- @class ClickableElement
--- @description Defines a clickable element's behavior, typically generated by functions in clickable_defs.lua
--- @field class number[] @Contains up to three class_type entries, left-click, right-click, and scrolling interactions (see class_type in clickable_common.lua)
--- @field hint string @Text to be displayed when hovering over this element in the cockpit
--- @field device number @ID of the device to connect to
--- @field action number[] @Command codes to be sent to the device on left-click, right-click, and scroll actions. must be a unique integer!
--- @field stop_action number[]|nil @Command codes to be sent to the device on RELEASE of left-click or right-click, resetting the element to a neutral value. Does not work with class_type.LEV
--- @field arg number[]|nil @Animation args to connect this element to. If set nil the element will not be able to remember its state!
--- @field arg_value number[] @For class_type.BTN and class_type.TUMB this is how much to increment per-click. For class_type.LEV it sets the starting value
--- @field arg_lim number[] @Numbers, this sets the range of animation of the element, and by extension the range of values the element can hold
--- @field cycle boolean? @Defaults true. If true, roll over upon exceeding a limit. If false, stop.
--- @field gain number[]|nil @unsure what this does but I suspect it's to do with class_type.LEV sensitivity
--- @field use_release_message boolean[]|nil @unsure what this does
--- @field sound table|nil @Game sounds to play when interacting, exact formatting unknown
--- @field updatable boolean|nil @Should this element's position be updated, ie is it animated? Use sparingly
--- @field use_OBB boolean|nil @Use Oriented Bounding Box
--- @field animated boolean[]|nil @Animated yes/no
--- @field animation_speed number[]|nil @Animation speeds

--- @type ClickableElement[]
elements = {}
