---------------------------------------------------------------------------
--- Various packages
---------------------------------------------------------------------------

------------------------------------------------------------------------------
--- lfs
------------------------------------------------------------------------------

--- @class lfs
--- @field add_location fun()
--- @field attributes fun(path:string, attribute:string):table @returns a table of file attributes (mode = file/directory, modification, size)
--- @field chdir fun(path:string) @changes the current directory.
--- @field create_lockfile fun()
--- @field currentdir fun():string @returns install directory.
--- @field del_location fun()
--- @field dir fun(path:string):table @returns a table of files and directories in the specified path.
--- @field locations fun():table @returns drives.
--- @field md5sum fun(path:string):string @returns the MD5 hash of a file.
--- @field mkdir fun(path:string) @creates a directory.
--- @field normpath fun(path:string):string @returns the normalized path.
--- @field realpath fun(path:string):string @returns the absolute path of a file.
--- @field rmdir fun(path:string) @removes a directory.
--- @field tempdir fun():string @returns the temporary directory.
--- @field writedir fun():string @returns the path to the saved games directory.

------------------------------------------------------------------------------
--- log
------------------------------------------------------------------------------

--- @class log
--- @field alert fun(message:string) @Logs an alert message.
--- @field debug fun(message:string) @Logs a debug message.
--- @field error fun(message:string) @Logs an error message.
--- @field info fun(message:string) @Logs an info message.
--- @field set_output fun()
--- @field set_output_rules fun()
--- @field warning fun(message:string) @Logs a warning message.
--- @field write fun()

------------------------------------------------------------------------------
--- dictionary
------------------------------------------------------------------------------

--- @class dictionary
--- @field addKeyToDict fun()
--- @field addNewLang fun()
--- @field clearDict fun()
--- @field clearResourceExceptDEFAULT fun()
--- @field copyFileInMission fun()
--- @field CopyKeysToNewDict fun()
--- @field deleteLang fun()
--- @field exchangeValue fun()
--- @field extractFirstDir fun()
--- @field extractSecondDir fun()
--- @field findDir fun()
--- @field fixDict fun()
--- @field fixValueToResource fun()
--- @field getBriefingData fun()
--- @field getCampaignData fun()
--- @field getCopyDictionary fun()
--- @field getCurDictionary fun()
--- @field getDictionary fun()
--- @field getFullPath fun()
--- @field getLangs fun()
--- @field getMapResource fun()
--- @field getMaxDictId fun()
--- @field getMissionDescription fun()
--- @field getNewDictId fun()
--- @field getNewResourceId fun()
--- @field getResourceCounter fun()
--- @field getValueDict fun()
--- @field getValueDictDEFAULT fun()
--- @field getValueResource fun()
--- @field getValueResourceDEFAULT fun()
--- @field intertFileIntoMission fun()
--- @field isLang fun()
--- @field isSignedMission fun()
--- @field loadDict fun()
--- @field loadDictionary fun()
--- @field packMissionResources fun()
--- @field removeFileFromMission fun()
--- @field removeKey fun()
--- @field removeResource fun()
--- @field removeResourceOnlyDict fun()
--- @field resetDictionary fun()
--- @field resourceExists fun()
--- @field setCurDictionary fun()
--- @field setMaxDictId fun()
--- @field setValueToDict fun()
--- @field setValueToDictEx fun()
--- @field setValueToResource fun()
--- @field showWarningMessageBox fun()
--- @field textToME fun()
--- @field textToMis fun()
--- @field unpackFiles fun()

------------------------------------------------------------------------------
--- Weather
------------------------------------------------------------------------------

--- @class Weather
--- @field getCloudsDensity fun()
--- @field getGroundWindAtPoint fun(pos)
--- @field getGroundWindComponents fun()
--- @field getGroundWindVelDir fun()
--- @field getTemperatureAndPressureAtPoint fun(pos) @returns temperature and pressure at a point. pos = {position = {x=0,y=0,z=0}}
--- @field getWindAtPoint fun()
--- @field getWindComponents fun()
--- @field getWindVelDir fun()
--- @field initAtmospere fun()
--- @field updateSpeedDirForOtherLevel fun()

------------------------------------------------------------------------------
--- sound
------------------------------------------------------------------------------

--- @class sound
--- @field exit fun()
--- @field getDevices fun()
--- @field getLayouts fun()
--- @field getWaveInfo fun()
--- @field init fun()
--- @field pauseMusic fun()
--- @field playMusic fun(playlist) @plays a playlist (table of filenames)
--- @field playPreview fun(file)
--- @field playSound fun(file)
--- @field resumeMusic fun()
--- @field setEffectsGain fun()
--- @field setMusicGain fun()
--- @field stopMusic fun()
--- @field stopPreview fun()
--- @field update fun()
--- @field updateSettings fun()

------------------------------------------------------------------------------
--- utils
------------------------------------------------------------------------------

--- @class utils
--- @field COLOR table
--- @field PI number
--- @field adv_round fun(value:number, maxAccuracy:number):number
--- @field angleDegrees fun(dd:number, mm:number, ss:number):number
--- @field bitor fun(x:number, y:number):number
--- @field copyTable fun(dest:table, src:table)
--- @field createTableCopy fun(src:table):table
--- @field dofileIn fun(filename:string, env:table):result,errmsg
--- @field dofileInEx fun(filename:string, env:table, base:table)
--- @field getTime fun(sec:number):number,number,number @returns hours, minutes, seconds
--- @field get_azimuth fun(vec:vec3):number
--- @field get_elevation fun(vec:vec3):number
--- @field get_lengthZX fun(vec:vec3):number
--- @field get_vec_length fun(vec:vec3):number
--- @field hasbit fun(x:number, p:number):boolean
--- @field invertColor fun(color:number):number
--- @field loadfileIn fun(filename:string, env:table):function,errmsg @loads a file in an environment.
--- @field makeColor fun(r:number, g:number, b:number):number
--- @field parseCordinates fun(str:string):number,number,number @returns latitude, longitude, course
--- @field round fun(value:number, accuracy:number):number
--- @field round_qty fun(qty:number):number
--- @field units table @units of measurement
--- @field verifyChunk fun(chunk:function, errmsg:string) @returns fun(x:number, parameters:table) with params set

------------------------------------------------------------------------------
--- db
------------------------------------------------------------------------------

--- @field Callnames table
--- @field Countermeasures table
--- @field Countries table
--- @field CountriesByName table
--- @field DefaultCountry table
--- @field FormationID table
--- @field Formations table
--- @field Pods table
--- @field Seasons table
--- @field Sensors table
--- @field Targets table
--- @field Units table
--- @field Weapons table
--- @field aircraftCallnames fun()
--- @field callnamesRussia table
--- @field declare_service_life_unit fun()
--- @field doesCallsignHasNumericPart fun()
--- @field getCallnames fun()
--- @field getCallnamesRefPoints fun()
--- @field getCountryOfOrigin fun()
--- @field getHistoricalCountres fun()
--- @field getUnitCallnames fun()
--- @field getUnitCallnames2 fun()
--- @field getYearsLauncher fun()
--- @field getYearsLocal fun()
--- @field isWesternCallnames fun()
--- @field localization table
--- @field objectIconByType table
--- @field rates table
--- @field roles table
--- @field typesNavPoints table
