OpsdcsCrew["SA342L"] = {
    options = {
        showHighlights = false,
        playSounds = false,
    },
    procedures = {
        {
            name = "Cold Start",
            start_state = "coldstart-before-startup",
        },
    },
    states = {
        -- Cold Start
        ["coldstart-before-startup"] = {
            text = "Before Startup",
            needAllPrevious = true,
            conditions = {
                { text = "Set roof lamp and UV lighting as required", cond = { "skip", }, hilights = { "INTER-BNL-PTR", "Lum_Plafond", "LENTILLE_PTR", "INTER-BNL-PTR" } },
                { text = "Set BATT switch to M", cond = { "arg_eq", "BATTERIE-PTR", 1 } },
                { text = "Check VOLT. between 23-29 V", cond = { "arg_between", "Aiguille_Volt", 0.367, 0.548 } },
                { text = "Check Q.COMB. for correct fuel amount", cond = { "skip" } },
                { text = "Check clock, wind and set", cond = { "skip" } },
                { text = "Set navigation lights F.POS to FIX or CLI", cond = { "arg_neq", "ANO-PTR", 0 } },
                { text = "Set anti-collision lights to NOR or ATT", cond = { "arg_neq", "FLASHER-PTR", 0 } },
                { text = "Set anti-collision intensity as required", cond = { "skip" }, hilights = { "ANTICOLL-INTENSITY-PTR" } },
                { text = "Set landing lights as required", cond = { "skip" }, hilights = { "LANDING-LIGHT-PTR" } },
                { text = "Set panel lighting to M, PUP and P.BO as required", cond = { "arg_eq", "PUPITRE-PLANCHEBORD-PTR", 1 } },
                { text = "Close doors", cond = { "arg_eq", "Copilot_Door", 0, "Pilot_Door", 0 } },
                { text = "Check fuel control lever closed", cond = { "arg_eq", "MANETTE-DEBIT-PTR", 0 } },
                { text = "Release rotor brake", cond = { "arg_eq", "FREIN-ROTOR-PTR", 1 } },
                { text = "Set GENE switch to M", cond = { "arg_eq", "GENE-PTR", 1 } },
                { text = "Set ALT switch to M", cond = { "arg_eq", "ALTER-PTR", 1 } },
            },
            next_state = "coldstart-flight-controls-check",
        },
        ["coldstart-flight-controls-check"] = {
            text = "Flight Controls Check",
            conditions = {
                { text = "Move cyclic full forward", cond = { "arg_gt", "StickPitch", 0.9 }, onlyOnce = true },
                { text = "Move cyclic full left", cond = { "arg_lt", "StickRoll", -0.9 }, onlyOnce = true },
                { text = "Move cyclic full back", cond = { "arg_lt", "StickPitch", -0.9 }, onlyOnce = true },
                { text = "Move cyclic full right", cond = { "arg_gt", "StickRoll", 0.9 }, onlyOnce = true },
                { text = "Move pedals full left", cond = { "arg_lt", "Rudder", -0.9 }, onlyOnce = true },
                { text = "Move pedals full right", cond = { "arg_gt", "Rudder", 0.9 }, onlyOnce = true },
                { text = "Center cyclic and pedals", cond = { "arg_between", "StickRoll", -0.05, 0.05, "arg_between", "StickPitch", -0.05, 0.05, "arg_between", "Rudder", -0.05, 0.05 }, needAllPrevious = true },
                { text = "Set DEBR.EFF switch to M", cond = { "arg_eq", "FMAG-PTR", 1 }, needAllPrevious = true },
                { text = "Move collective full up", cond = { "arg_gt", "Collective", 0.9 }, needAllPrevious = true, onlyOnce = true },
                { text = "Move collective full down", cond = { "arg_lt", "Collective", 0.05 }, needAllPrevious = true },
                { text = "Hold general TEST and check all lights", cond = { "arg_eq", "TEST-TA-PTR", 1, "arg_range_between", "1-13", 1, 1 }, needAllPrevious = true, onlyOnce = true },
                { text = "Hold voltmeter TEST and check all lights", cond = { "arg_eq", "VATEST-PTR", 1, "arg_range_between", "201-203,300-303,320-322,1330-1334", 1, 1 }, needAllPrevious = true, onlyOnce = true },
                { text = "Set altimeter barometric pressure setting", cond = { "skip" }, needAllPrevious = true },
                { text = "Set max torque index according to chart", cond = { "arg_gt", "Torque_Bug_multi", 64 }, needAllPrevious = true },
            },
            next_state = "coldstart-radio-setup"
        },
        ["coldstart-radio-setup"] = {
            text = "Radio Setup",
            needAllPrevious = true,
            conditions = {
                { text = "Set UHF power knob to FF or as required", cond = { "arg_eq", "UHF_isOn", 1 }, onlyOnce = true },
                { text = "Wait for BIT to complete", cond = { "skip" }, duration = 10 },
                { text = "Set UHF frequency as required", cond = { "skip" } },
                { text = "Select UHF radio on pilot intercom panel, adjust volume as required", cond = { "arg_eq", "IC1-UHF-PTR", 1 }, onlyOnce = true },
                { text = "Contact ATC and request startup (optional)", cond = { "skip" } },
                { text = "Set VHF radio mode to TEST and check tone", cond = { "arg_gt", "VHF-SQ-BAS-PTR", 0.98 }, onlyOnce = true },
                { text = "Set VHF radio mode to SIL or M", cond = { "arg_between", "VHF-SQ-BAS-PTR", 0.32, 0.68 }, onlyOnce = true },
                { text = "Check VHF power light is ON", cond = { "arg_eq", "AM_Radio_lamp", 1 }, onlyOnce = true },
                { text = "Set VHF AM radio frequency as required", cond = { "skip" } },
                { text = "Adjust VHF radio volume as required", cond = { "skip" } },
                { text = "Set FM radio mode to TRAFFIC", cond = { "arg_eq", "FM-MAIN-PTR", 0.25 }, onlyOnce = true },
                { text = "Set FM preset channel as required", cond = { "skip" } },
                { text = "Adjust FM radio volume as required", cond = { "skip" } },
                { text = "Set NAV mode rotator to ADF or as required", cond = { "arg_gt", "ADF_MODE_PTR", 0 }, onlyOnce = true },
                { text = "Set ADF frequency as required", cond = { "skip" } },
            },
            next_state = "coldstart-engine-start"
        },
        ["coldstart-engine-start"] = {
            text = "Engine Start",
            needAllPrevious = true,
            conditions = {
                { text = "Set POMPE to M", cond = { "arg_eq", "FUEL-PUMP-FRONT-PTR", 1 } },
                { text = "Start stop-watch timer and wait 20 sec", cond = { "arg_gt", "Clock_seconde", 0.3 }, onlyOnce = true },
                { text = "Reset the stop-watch", cond = { "arg_eq", "Clock_seconde", 0 }, onlyOnce = true },
                { text = "Set starter switch DEM. to M", cond = { "arg_eq", "INTER-MA-PTR", 1 } },
                { text = "Check DEM lamp is ON", cond = { "arg_eq", "Voyant_DEM", 1 }, onlyOnce = true },
                { text = "Check turbine speed increases", cond = { "arg_gt", "Turbine_RPM", 0.1 } },
                { text = "Confirm DEM lamp OFF once turbine reaches IDLE RPM", cond = { "arg_gt", "Turbine_RPM", 0.5, "arg_eq", "Voyant_DEM", 0 } },
                { text = "Check T4 engine temp rises", cond = { "arg_between", "Aiguille_TQuatre", 0.2, 0.6 } },
                { text = "Push Fuel Flow control lever forward until rotor starts spinning", cond = { "param_gt", "BASE_SENSOR_PROPELLER_RPM", 0 } },
                { text = "Wait for turbine and main rotor RPM to sync", cond = { "arg_diff_lt", "Turbine_RPM", "Rotor_RPM", 0.05 } },
                { text = "Slowly move fuel lever forward", cond = { "arg_eq", "MANETTE-DEBIT-PTR", 1 } },
                { text = "Check HBTP and HMOT oil pressure lights off", cond = { "arg_eq", "TA_HBTP", 0, "arg_eq", "TA_HMOT", 0 } },
                { text = "Check T4 temp decrease once above 35000 RPM", cond = { "arg_gt", "Turbine_RPM", 0.664 } },
                { text = "Wait for turbine RPM 43500 and rotor RPM 387", cond = { "arg_gt", "Turbine_RPM", 0.77, "arg_gt", "Rotor_RPM", 0.77 } },
                { text = "Check ALARME light is OFF", cond = { "arg_eq", "Voyant_ALARME", 0 } },
            },
            next_state = "coldstart-post-start"
        },
        ["coldstart-post-start"] = {
            text = "Post Start",
            needAllPrevious = true,
            conditions = {
                { text = "Set PITOT Heat Switch to M", cond = { "arg_eq", "PITOT-PTR", 1 } },
                { text = "Set TRIM Switch to M", cond = { "arg_eq", "TRIM-PTR", 1 } },
                { text = "Set R.SUPP and R.CONV switches to A", cond = { "arg_eq", "RCONV-PTR", 0, "arg_eq", "RSUPP-PTR", 0 } },
                { text = "Set sand filter FILT.AS to M", cond = { "arg_eq", "FILTAS-PTR", 1 } },
                { text = "Check VOLT. between 23-29 V", cond = { "arg_between", "Aiguille_Volt", 0.367, 0.548 } },
                { text = "Check warning panel all lights OFF (except PA)", cond = { "arg_range_between", "1-7,9-13", 0, 0 } },
                { text = "Switch on wipers if required", cond = { "skip" } },
                { text = "Set gyro mode selector to GM to start alignment", cond = { "arg_eq", "GYRO-KNOB-GD-PTR", 0.5 } },
                { text = "Set NADIR DOPPLER to VEILLE", cond = { "arg_eq", "NADIR_DOPPLER", 0.2 } },
                { text = "Rotate radar altimeter switch to M", cond = { "arg_eq", "Knob_RAlt_OnOFF", 1 } },
                { text = "Test altimeter by click and hold", cond = { "arg_eq", "RALT-ONOFF-PTR", 1, "arg_eq", "RAlt_Flag_Panne", 1 }, onlyOnce = true },
                { text = "Set danger altitude as required", cond = { "skip" } },
                { text = "Uncage Main ADI and wait until it stops moving", cond = { "arg_eq", "HA-PTR", 1 }, onlyOnce = true, duration = 3 },
                { text = "Set Main ADI selector to DOP", cond = { "arg_eq", "ArtVisVhfDop-PTR", 0.99 } },
                { text = "Uncage Standby ADI", cond = { "arg_eq", "Stdby_HA_flag", 0 }, onlyOnce = true },
            },
            next_state = "coldstart-post-start-2"
        },
        ["coldstart-post-start-2"] = {
            text = "Post Start",
            needAllPrevious = true,
            conditions = {
                { text = "Wait for GYRO alignment GYRO and AMPLI are ON", cond = { "arg_eq", "GYRO_Flags", 0 } },
                { text = "Set Autopilot Pitch, Roll and Yaw to M", cond = { "arg_eq", "PA_TANGAGE_PTR", 1, "arg_eq", "PA_ROULIS_PTR", 1, "arg_eq", "PA_LACET_PTR", 1 } },
                { text = "Set Autopilot Power to M", cond = { "arg_eq", "PA_MASTER_PTR", 1 } },
                { text = "Check PA warning light OFF", cond = { "arg_eq", "TA_PA", 0 } },
                { text = "Check NADIR ERR, AIR and NAV cautions are OFF", cond = { "param_eq", "E_ERR_vis", 0, "param_eq", "E_AIR_vis", 0, "param_eq", "E_NAV_vis", 0 } },
                { text = "Set NADIR DOPPLER to TERRE", cond = { "arg_eq", "NADIR_DOPPLER", 0.4 } },
                { text = "Enter waypoints if required", cond = { "skip" } },
                { text = "Set NADIR parameter to BUT", cond = { "arg_eq", "NADIR_VENT", 1 } },
                { text = "Set DRAX33 RWR switch to ON", cond = { "arg_eq", "RWR-ON-OFF-PTR", 0 } },
                { text = "Set LANCE-LEURRES power switch to VE or LE", cond = { "arg_gt", "FD-VE-PTR", -1 } },
                { text = "Set LANCE-LEURRES mode as required", cond = { "skip" } },
                { text = "Open Flare Dispenser Cover Switch", cond = { "arg_eq", "FD-FIRE-BUTTON-CAP-PTR", 1 } },
                --{ text = "Set IFF power to ON", cond = { "arg_eq", "IFF-SWITCH1-PTR", 1 } },
                --{ text = "Set IFF mode to N and codes as required", cond = { "arg_eq", "IFF-KNOB2-PTR", 0.66 } },
                { text = "Deploy EFB and set Power to ON if required", cond = { "skip" }, hilights = { "Tablet_fold" } },
            },
            next_state = "coldstart-complete"
        },
        ["coldstart-complete"] = {
            text = "Cold start complete",
        },
    },
    args = {
        ["TA_PITOT"] = 1,
        ["TA_HMOT"] = 2,
        ["TA_HBTP"] = 3,
        ["TA_HRAL"] = 4,
        ["TA_GENE"] = 5,
        ["TA_ALTER"] = 6,
        ["TA_BAT"] = 7,
        ["TA_PA"] = 8,
        ["TA_NAV"] = 9,
        ["TA_COMB"] = 10,
        ["TA_BPHY"] = 11,
        ["TA_LIM"] = 12,
        ["TA_FILT"] = 13,
        ["Aiguille_Volt"] = 14,
        ["Aiguille_TQuatre"] = 15,
        ["Aiguille_Torque"] = 16,
        ["Voyant_Torque"] = 17,
        ["HA_flag_GS"] = 18,
        ["HA_flag_HS"] = 19,
        ["HA_bille"] = 20,
        ["PUP-PTR"] = 21,
        ["PBO-PTR"] = 22,
        ["INTER-BNL-PTR"] = 23,
        ["Variometre"] = 24,
        ["TempExt"] = 25,
        ["Heading"] = 26,
        ["HA_Pitch"] = 27,
        ["HA_Roll"] = 28,
        ["HA_flag_LOC"] = 29,
        ["ANTICOLL-INTENSITY-PTR"] = 30,
        ["PA_MASTER_PTR"] = 31,
        ["PA_TANGAGE_PTR"] = 32,
        ["PA_ROULIS_PTR"] = 33,
        ["PA_LACET_PTR"] = 34,
        ["PA_MODE_PTR"] = 35,
        ["Aiguille_Tangage"] = 37,
        ["Aiguille_Roulis"] = 38,
        ["Aiguille_Lacet"] = 39,
        ["LENTILLE_PTR"] = 40,
        ["Clock_heure"] = 41,
        ["Clock_seconde"] = 42,
        ["Clock_minute"] = 43,
        ["Clock_mini"] = 44,
        ["Clock_Wind"] = 45,
        ["Clock_StartStop"] = 46,
        ["Clock_Reset"] = 47,
        ["EG-COPILOTE-PTR"] = 48,
        ["EG-PILOTE-PTR"] = 49,
        ["DEB-EFF-PTR"] = 50,
        ["IAS"] = 51,
        ["Rotor_RPM"] = 52,
        ["EG-STICK-PTR"] = 53,
        ["Alert_Pourcent"] = 54,
        ["Curseur_Alert_Pourcent"] = 55,
        ["INTER-MA-PTR"] = 56,
        ["TEST-TA-PTR"] = 57,
        ["TORQUE-PTR"] = 58,
        ["HYD-PTR"] = 59,
        ["TRIM-PTR"] = 60,
        ["SPACE-PTR"] = 61,
        ["VATEST-PTR"] = 62,
        ["RCONV-PTR"] = 63,
        ["FILTAS-PTR"] = 64,
        ["FMAG-PTR"] = 65,
        ["REARM-ALTER-PTR"] = 66,
        ["REARM-GENE-PTR"] = 67,
        ["StickRoll"] = 71,
        ["StickPitch"] = 74,
        ["Altimeter_thousands"] = 87,
        ["Altimeter_Press_unite"] = 88,
        ["BALT-PTR"] = 89,
        ["Altimeter_Press_dix"] = 90,
        ["Knob_RAlt_OnOFF"] = 91,
        ["Altimeter_Press_cent"] = 92,
        ["DangerRALT"] = 93,
        ["Radar_Altimeter"] = 94,
        ["Altimeter_Press_mille"] = 95,
        ["RALT-DANGERALT-PTR"] = 96,
        ["RAlt_Alarm"] = 97,
        ["RAlt_Flag_Panne"] = 98,
        ["RAlt_Flag_MA_OnOff"] = 99,
        ["RALT-ONOFF-PTR"] = 100,
        ["IC2_RC"] = 101,
        ["ADF_AiguilleLarge"] = 102,
        ["ADF_AiguilleFine"] = 103,
        ["Collective"] = 104,
        ["LANDING-LIGHT-PTR"] = 105,
        ["LANDING-LIGHT-EXTEND-PTR"] = 106,
        ["ADF_Flag_CAP"] = 107,
        ["ADF_Flag_Compteur"] = 108,
        ["ADF_Flag_But"] = 109,
        ["ADF_100"] = 110,
        ["ADF_10"] = 111,
        ["ADF_1"] = 112,
        ["ADF_Fond"] = 113,
        ["inter_Servo"] = 114,
        ["HA_Rot"] = 115,
        ["HA-PTR"] = 116,
        ["HA_Curseur"] = 117,
        ["HA_barre_Verticale"] = 118,
        ["HA_barre_Horizontale"] = 119,
        ["HA_W"] = 120,
        ["RWR_audio"] = 121,
        ["RWR_brt"] = 122,
        ["TV_Brt"] = 123,
        ["TV_inter"] = 124,
        ["TV_Lum"] = 125,
        ["TV_Cache"] = 126,
        ["TV_Lamp"] = 127,
        ["VHF-SQ-BAS-PTR"] = 128,
        ["VHF-SQ-HAUT-PTR"] = 129,
        ["VHF-FREQ-BAS-PTR"] = 130,
        ["VHF-FREQ-HAUT-PTR"] = 131,
        ["AM_Radio_freq_cent"] = 133,
        ["AM_Radio_freq_dix"] = 134,
        ["Turbine_RPM"] = 135,
        ["AM_Radio_freq_unite"] = 136,
        ["QCOMB"] = 137,
        ["AM_Radio_freq_dixieme"] = 138,
        ["AM_Radio_freq_centieme"] = 139,
        ["AM_Radio_lamp"] = 141,
        ["PBO_Intensity"] = 142,
        ["PUP_Intensity"] = 144,
        ["INTER-BNL-PTR"] = 145,
        ["ANO-PTR"] = 146,
        ["KNOB-PLAFOND-PTR"] = 147,
        ["RWR-ON-OFF-PTR"] = 148,
        ["RWR-MARQUEUR-PTR"] = 149,
        ["RWR-PAGE-PTR"] = 150,
        ["TempThm"] = 151,
        ["Rsupp_aiguille"] = 152,
        ["GYRO-KNOB-GD-PTR"] = 153,
        ["LENTILLE_PTR"] = 154,
        ["Gun_Mounted"] = 155,
        ["ADF_SELECT_PTR"] = 166,
        ["ADF_TONESWITCH_PTR"] = 167,
        ["ADF_LLOWKNOB_PTR"] = 168,
        ["ADF_LMIDKNOB_PTR"] = 169,
        ["PITOT-PTR"] = 170,
        ["PILOTSIGHT-PTR"] = 171,
        ["Athos_Periscope"] = 172,
        ["ADF_MODE_PTR"] = 178,
        ["ADF_GAIN_PTR"] = 179,
        ["PV_CLE_PTR"] = 180,
        ["PV-GISEMENT-PTR"] = 181,
        ["PV_LUM_PTR"] = 182,
        ["PH_Bon_Light"] = 183,
        ["PH_Mauvais_Light"] = 184,
        ["PH_Alim_Light"] = 185,
        ["PH_Pret_Light"] = 186,
        ["PH_Autor_Light"] = 187,
        ["PH_Defaut_Light"] = 188,
        ["PH_TestI_Light"] = 189,
        ["PH_Jour_Light"] = 190,
        ["PH_Lum_Light"] = 191,
        ["PH_TestII_Light"] = 192,
        ["PH_Nuit_Light"] = 193,
        ["FD-FIRE-BUTTON-CAP-PTR"] = 194,
        ["FD-FIRE-BUTTON-PTR"] = 195,
        ["RWR_light"] = 196,
        ["GYRO-TEST-COVER-PTR"] = 197,
        ["GYRO-TEST-SWITCH-PTR"] = 198,
        ["GYRO-SWITCH-GD-PTR"] = 199,
        ["GYRO_Needle"] = 200,
        ["GYRO_voyant_test"] = 201,
        ["GYRO_voyant_trim"] = 202,
        ["GYRO_voyant_bpp"] = 203,
        ["GYRO_Flags"] = 208,
        ["Pilot_Stick_PA"] = 209,
        ["Clock_ExtCouronne"] = 210,
        ["Stdby_HA_flag"] = 211,
        ["Stdby_HA_W"] = 212,
        ["Stdby_HA_Pitch"] = 213,
        ["Stdby_HA_Roll"] = 214,
        ["Stdby_HA_butRot"] = 215,
        ["StdbyHA-PTR"] = 216,
        ["Stdby_HA_Curseur"] = 217,
        ["ArtVisVhfDop-PTR"] = 218,
        ["WS_INCRUST_PTR"] = 219,
        ["FD-OPE-PTR"] = 220,
        ["FD-CC-SEQ-PTR"] = 221,
        ["FD-VE-PTR"] = 222,
        ["FD_lamp_G_vide1"] = 223,
        ["FD_lamp_G_vide2"] = 224,
        ["FD_lamp_D_vide1"] = 225,
        ["FD_lamp_D_vide2"] = 226,
        ["FD_lamp_LEU"] = 227,
        ["FLASHER-PTR"] = 228,
        ["FEUX-FORMATION-INTER-PTR"] = 229,
        ["FEUX-FORMATION-INTENSITY-PTR"] = 230,
        ["FD_lamp_G_OPE"] = 231,
        ["FD_lamp_D_OPE"] = 232,
        ["FD_lamp_VE"] = 233,
        ["IFF-KNOB2-PTR"] = 245,
        ["IFF-SWITCH1-PTR"] = 246,
        ["BATTERIE-PTR"] = 264,
        ["ALTER-PTR"] = 265,
        ["Rudder"] = 266,
        ["RSUPP-PTR"] = 267,
        ["GENE-PTR"] = 268,
        ["MASTER_ARM_PTR"] = 269,
        ["CLOCK-WINDER-PTR"] = 270,
        ["FUEL-PUMP-FRONT-PTR"] = 271,
        ["FM-MAIN-PTR"] = 272,
        ["Active_seat"] = 291,
        ["TV_halo"] = 292,
        ["HA_Curseur_multi"] = 295,
        ["stdbyHA_Curseur_multi"] = 296,
        ["Clock_Couronne_multi"] = 297,
        ["Clock_delta_multi"] = 298,
        ["Torque_Bug_multi"] = 299,
        ["Voyant_DEM"] = 300,
        ["Voyant_RLT"] = 301,
        ["Voyant_BLOC"] = 302,
        ["Voyant_ALARME"] = 303,
        ["Baro_pressure_multi"] = 312,
        ["RadAlt_Bug_multi"] = 313,
        ["AM_Freq_multi"] = 314,
        ["Voyant_RSUPP"] = 320,
        ["Voyant_RCONV"] = 321,
        ["Voyant_FILTAS"] = 322,
        ["NADIR_DOPPLER"] = 331,
        ["NADIR_VENT"] = 332,
        ["WP1_ONOFF"] = 354,
        ["WP1_BRT"] = 357,
        ["PUPITRE-PLANCHEBORD-PTR"] = 382,
        ["UHF_KNOB"] = 383,
        ["UHF_isOn"] = 398,
        ["Collective_multi"] = 411,
        ["Stick_Pitch_multi"] = 412,
        ["Stick_Roll_multi"] = 413,
        ["Rudder_multi"] = 414,
        ["WP1_left_ammo"] = 450,
        ["WP1_right_ammo"] = 451,
        ["IC1-VHF-PTR"] = 452,
        ["IC1-FM1-PTR"] = 453,
        ["IC1-UHF-PTR"] = 454,
        ["IC2-VHF-PTR"] = 455,
        ["IC2-FM1-PTR"] = 456,
        ["IC2-UHF-PTR"] = 457,
        ["Copilot_Door"] = 532,
        ["Pilot_Door"] = 533,
        ["FREIN-ROTOR-PTR"] = 556,
        ["MANETTE-DEBIT-PTR"] = 557,
        ["Manette_Coupe_Feu"] = 558,
        ["Pilot_Mic_Lamp_multi"] = 559,
        ["CoPilot_Mic_Lamp_multi"] = 562,
        ["IRSeeker_sound_multi"] = 565,
        ["VivAzimuth_multi"] = 566,
        ["VivElevation_multi"] = 567,
        ["VivAzimuthState_multi"] = 568,
        ["VivElevationState_multi"] = 569,
        ["HA_Unlock_multi"] = 570,
        ["stdbyHA_Unlock_multi"] = 571,
        ["Altimeter_tenth"] = 573,
        ["Athos_Periscope"] = 575,
        ["Tablet_fold"] = 610,
        ["Tablet_vis"] = 611,
        ["IN_ALV_YELLOW_ONOFF"] = 1330,
        ["IN_ALV_GREEN_ONOFF"] = 1331,
        ["IN_CVS_YELLOW_ONOFF"] = 1332,
        ["IN_CVS_GREEN_ONOFF"] = 1333,
        ["IN_AP_LIGHTS_BRT"] = 1334,
        ["REMOVE_DOORS"] = 1337,
        ["AMMO_BOX_GIAT"] = 1340,
        ["REAR_SEATS"] = 1400,
    },
    excludeDebugArgs = {
        [422] = true, --anim
        [423] = true, --anim
        [532] = true, --doors
        [533] = true, --doors
        [548] = true, --anim
        [549] = true, --anim
        [552] = true, --anim
        [553] = true, --anim
    },
    params = {
        "E_PILE_vis",
        "E_GEL_vis",
        "E_nGEL_vis",
        "E_AIR_vis",
        "E_ERR_vis",
        "E_NAV_vis",
        "E_PANNE_vis",
    },
    indications = {
        [1] = {
        },
        [2] = {
        },
        [3] = {
        }
    },
    commands = {},
}
