OpsdcsCrew["UH-1H"] = {
    options = {
        showHighlights = true,
        playSounds = false,
    },
    procedures = {
        {
            name = "Cold Start",
            start_state = "coldstart-before-engine-start",
        },
    },
    states = {
        -- Cold Start
        ["coldstart-before-engine-start"] = {
            text = "Before Engine Start",
            needAllPrevious = true,
            conditions = {
                { text = "DC circuit breakers IN, except armament/special equip", cond = { "skip" } }, -- why except?
                { text = "ANTI-COLL to ON, DOME LT as required", cond = { "arg_eq", "ANTI-COLL-PTR", 1 } },
                { text = "AC Voltmeter to AC PHASE", cond = { "arg_eq", "PHASE-SWITCHER-PTR", 0.1 } },
                { text = "AC INVTR switch to OFF", cond = { "arg_eq", "INVTR-SWITCHER-PTR", 0 } },
                { text = "DC MAIN GEN switch to ON, cover down", cond = { "arg_eq", "MAIN-GEN-SWITCHER-PTR", -1, "arg_eq", "MAIN-GEN-SWITCHER-COVER-PTR", 0 } },
                { text = "DC VM selector to ESS BUS", cond = { "arg_eq", "VM-SWITCHER-PTR", 0.3 } },
                { text = "DC NON-ESS BUS switch to NORMAL", cond = { "arg_eq", "NON-ESS-BUS-SWITCHERr-PTR", 0 } },
                { text = "DC STARTER GEN switch to START", cond = { "arg_eq", "STARTER-GEN-SWITCHERr-PTR", 1 } },
                { text = "DC BAT switch ON", cond = { "arg_eq", "BAT-SWITCHER-PTR", 0 } },
                { text = "Set LOW RPM to OFF", cond = { "arg_eq", "LOW-RPM-PTR", 0  } },
                { text = "Test FIRE warning indicator light", cond = { "arg_eq", "FIRE-DETECTOR-PTR", 1 }, onlyOnce = true },
                { text = "Caution panel lights TEST, check lights", cond = { "arg_eq", "RESET-TEST-SWITCH-PTR", -1 }, onlyOnce = true },
                { text = "Caution panel lights RESET", cond = { "arg_eq", "RESET-TEST-SWITCH-PTR", 1 }, onlyOnce = true },
                { text = "Check external stores jettison handle safe tied", cond = { "skip" } }, --??
                { text = "Check ARM/STBY/SAFE switch is SAFE", cond = { "arg_eq", "ARMED-SWITCH-PTR", -1 } },
                { text = "Check JETTISON switch down and covered", cond = {"arg_eq", "JETT-COVER-PTR", 0, "arg_eq", "JETT-SWITCH-PTR", 0 } },
                { text = "GOV switch to AUTO", cond = { "arg_eq", "GOV-PTR", 1 } },
                { text = "DE-ICE switch to OFF", cond = { "arg_eq", "DE-ICE-PTR", 0 } },
                { text = "MAIN FUEL switch to ON", cond = { "arg_eq", "FUEL-PTR", 1 } },
                { text = "All other FUEL switches to OFF", cond = { "skip" } },
            },
            next_state = "coldstart-flight-controls-check",
        },
        ["coldstart-flight-controls-check"] = {
            text = "Flight Controls Check",
            conditions = {
                { text = "HYD CONT switch to ON", cond = { "arg_eq", "HYD-CONT-PTR", 1 } },
                { text = "FORCE TRIM switch to ON", cond = { "arg_eq", "FORCE-TRIM-PTR", 1 }, needAllPrevious = true },
                { text = "CHIP DET switch to BOTH", cond = { "arg_eq", "CHIP-DET-PTR", 0 }, needAllPrevious = true },
                { text = "Move Cyclic full forward", cond = { "arg_lt", "PITCH", -0.9 }, onlyOnce = true },
                { text = "Move Cyclic full left", cond = { "arg_lt", "ROLL", -0.65 }, onlyOnce = true },
                { text = "Move Cyclic full back", cond = { "arg_gt", "PITCH", 0.9 }, onlyOnce = true },
                { text = "Move Cyclic full right", cond = { "arg_gt", "ROLL", 0.65 }, onlyOnce = true },
                { text = "Move Pedals full left", cond = { "arg_lt", "RUDDER", -0.8 }, onlyOnce = true },
                { text = "Move Pedals full right", cond = { "arg_gt", "RUDDER", 0.8 }, onlyOnce = true },
                { text = "Move Collective full up", cond = { "arg_gt", "COLLECTIVE", 0.9 }, onlyOnce = true },
                { text = "Move Collective full down", cond = { "arg_eq", "COLLECTIVE", 0 }, needAllPrevious = true },
                { text = "Center cyclic and pedals", cond = { "arg_between", "ROLL", -0.05, 0.05, "arg_between", "PITCH", -0.05, 0.05, "arg_between", "RUDDER", -0.05, 0.05 }, needAllPrevious = true },
            },
            next_state = "coldstart-starting-engine",
        },
        ["coldstart-starting-engine"] = {
            text = "Engine Start",
            needAllPrevious = true,
            conditions = {
                { text = "Roll throttle to FULL OPEN", cond = { "arg_eq", "THROTTLE-1-PTR", -1 }, onlyOnce = true },
                { text = "Roll throttle back to IDLE STOP", cond = { "arg_eq", "THROTTLE-1-PTR", 0 }, onlyOnce = true },
                { text = "Engage throttle stop switch", cond = { "arg_eq", "ENGINE-BTN-1-PTR", 1 }, onlyOnce = true },
                { text = "Roll throttle slightly right of IDLE", cond = { "arg_gt", "THROTTLE-1-PTR", 0 }, onlyOnce = true },
                { text = "Release throttle stop switch", cond = { "arg_eq", "ENGINE-BTN-1-PTR", 0 }, onlyOnce = true },
                { text = "Press and hold START switch", cond = {  }, onlyOnce = true },
                { text = "Wait for N1 reaching 15%", cond = {  } },
                { text = "Check main rotor is turning", cond = {  } },
                { text = "Wait for N1 reaching 40%", cond = {  } },
                { text = "Release START switch", cond = {  } },
                { text = "Advance throttle to IDLE, check idle stop", cond = {  }, onlyOnce = true },
                { text = "Wait for N1 reaching 68-72%", cond = {  } },
                { text = "Check engine and transmission oil pressures", cond = {  } },
            },
            next_state = "coldstart-engine-runup",
        },
        ["coldstart-starting-engine"] = {
            text = "Engine Runup",
            needAllPrevious = true,
            conditions = {
                { text = "INVTR switch to MAIN ON", cond = {  } },
                { text = "STARTER GEN switch to STBY GEN", cond = {  } },
                { text = "Advance throttle slowly to FULL", cond = {  } },
                { text = "Systems check - FUEL", cond = {  } },
                { text = "Systems check - Engine", cond = {  } },
                { text = "Systems check - Transmission", cond = {  } },
                { text = "Systems check - AC 112-118 Volts", cond = {  } },
                { text = "Systems check - DC 27-28.5 Volts", cond = {  } },
                { text = "Check low RPM warning OFF at 6100-6300 RPM", cond = {  } },
                { text = "Wait for RPM reach 6600", cond = {  } },
            },
            next_state = "coldstart-setup-avionics",
        },
        ["coldstart-setup-avionics"] = {
            text = "Setup Avionics",
            conditions = {
                { text = "Set baro altimeter to field evelation", cond = {  } },
                { text = "Sync gyro compass to magnetic heading", cond = {  } },
                { text = "Radar altimeter power to ON", cond = {  } },
                { text = "Radar altimeter LO and HIGH as required", cond = {  } },
                { text = "IFF MASTER to NORM", cond = {  } },
                { text = "IFF MODE 4 to ON", cond = {  } },
                { text = "Set NAV COMM as required", cond = {  } },
                { text = "Set VHF COMM PWR to ON", cond = {  } },
                { text = "Set FM COMM Mode to T/R", cond = {  } },
                { text = "Set ADF Mode as required ", cond = {  } },
                { text = "Set UHF Mode to T/R", cond = {  } },
            },
            next_state = "coldstart-complete"
        },
        ["coldstart-complete"] = {
            text = "Cold start complete",
        },
    },
    args = {
        ["MHZ-SELECTOR-PTR"]  = 7,
        ["KHZ-SELECTOR-PTR"] = 8,
        ["MODE-SWITCH-PTR"] = 35,
        ["TUNE-CONTROL-PTR"] = 39,
        ["BFO-SWITCH-PTR"] = 41,
        ["GAIN-CONTROL-PTR"] = 44,
        ["WHOLE-MHZ-SELECTOR-KNOB-PTR"]  = 52,
        ["FRACTIONAL-MHZ-SELECTOR-KNOB-KNOB-PTR"] = 53,
        ["VOLUME-OFF-INCR-CONTROL-PTR"]  = 57,
        ["CODE-PTR"]= 58,
        ["MASTER-CONTROL-PTR"] = 59,
        ["MODE-4-SWITCH-PTR"]= 67,
        ["LOW-RPM-PTR"] = 80,
        ["FUEL-PTR"] = 81,
        ["DE-ICE-PTR"] = 84,
        ["GOV-PTR"] = 85,
        ["CHIP-DET-PTR"] = 86,
        ["FORCE-TRIM-PTR"] = 89,
        ["HYD-CONT-PTR"] = 90,
        ["RESET-TEST-SWITCH-PTR"] = 111,
        ["CAGING-KNOB-ROTATION-PTR"] = 140,
        ["PILOT-ATT-PITCH-ADJ-KNOB-PTR"] = 144,
        ["PILOT-ATT-ROLL-ADJ-KNOB-PTR"] = 145,
        ["CDI-OBS-PTR"] = 155,
        ["HDG-SYNC-PTR"] = 161,
        ["HDG-SET-PTR"] = 163,
        ["ADF-VOR-PTR"] = 164,
        ["PILOT-ALT-SET-KNOB-PTR"] = 181,
        ["RUDDER"] = 184,
        ["PITCH"] = 186,
        ["ROLL"] = 187,
        ["COLLECTIVE"] = 200,
        ["ENGINE-BTN-1-PTR"] = 206,
        ["PHASE-SWITCHER-PTR"] = 214,
        ["INVTR-SWITCHER-PTR"] = 215,
        ["MAIN-GEN-SWITCHER-PTR"] = 216,
        ["MAIN-GEN-SWITCHER-COVER-PTR"] = 217,
        ["VM-SWITCHER-PTR"] = 218,
        ["BAT-SWITCHER-PTR"] = 219,
        ["STARTER-GEN-SWITCHERr-PTR"] = 220,
        ["NON-ESS-BUS-SWITCHERr-PTR"] = 221,
        ["ANTI-COLL-PTR"] = 225,
        ["FUEL-GAUGE-PTR"] = 240,
        ["DG-SLAVE-PTR"] = 241,
        ["THROTTLE-1-PTR"] = 250,
        ["ARMED-SWITCH-PTR"] = 252,
        ["LRGUN-SWITCH-PTR"] = 253,
        ["762-SWITCH-PTR"] = 256,
        ["RKT-PAIR-PTR"] = 257,
        ["RKT-RESET-PTR"] = 258,
        ["JETT-COVER-PTR"] = 259,
        ["JETT-SWITCH-PTR"] = 260,
        ["FIRE-DETECTOR-PTR"] = 278,
        ["PITCH-LO-ALT-PTR"] = 445,
        ["PITCH-HI-ALT-PTR"] = 446,
        ["RADAR-ALT-PTR"] = 449,
        ["CHAFF-ARM-SWITCH-PTR"] = 456,
        ["PGRM-SWITCH-PTR"] = 459,
        ["FLARE-DISP-PTR"] = 464,

    },
    excludeDebugArgs = {
        [132] = true,
        [133] = true,
        [185] = true,
        [190] = true,
        [191] = true,
        [207] = true,
        [243] = true,
        [244] = true,
        [246] = true,
        [247] = true,
        [264] = true,
        [265] = true,
    },
    params = {
    },
    indications = {
        [1] = {
        },
        [2] = {
        },
        [3] = {
        }
    },
    commands = {},
}
