--- @class avIntercom:Device
--- @field easy_comm_override string @function
--- @field get_noise_level string @function
--- @field get_signal_level string @function
--- @field is_communicator_available string @function
--- @field make_setup_for_communicator string @function
--- @field set_communicator string @function
