--- @class avSimpleWeaponSystem:Device
--- @field SetDamage string @function
--- @field drop_chaff fun(count:number, dispenser:number) @see chaff_flare_dispenser in aircraft definition
--- @field drop_flare fun(count:number, dispenser:number) @see chaff_flare_dispenser in aircraft definition
--- @field emergency_jettison string @function
--- @field emergency_jettison_rack string @function
--- @field get_ECM_status string @function
--- @field get_chaff_count fun():number @get chaff count
--- @field get_flare_count fun():number @get flare count
--- @field get_station_info string @function
--- @field get_target_range string @function
--- @field get_target_span string @function
--- @field launch_station fun(self:Device, station:number) @launch station (weapon system device)
--- @field select_station fun(self:Device, station:number) @select station (weapon system device)
--- @field set_ECM_status string @function
--- @field set_target_range string @function
--- @field set_target_span string @function
