-- This file is responsible for containing your cockpit coordinates with ESM (your Views.lua file is ignored with a systems model) and your gauges.
-- Either base gauges, which are the main animations ie. Mach Number or Stick Roll, or the parameter gauges.
