------------------------------------------------------------------------------
--- Radio commands
---
--- available in this script:
--- utils class
--- db class
--- data (radio commands data)
--- data.base (gui env)
------------------------------------------------------------------------------
