-- todo: voices + voice checklist logic

OpsdcsCrew["OH58D"] = {
    procedures = {
        ["coldstart"] = {
            text = "Cold Start",
            cond = { "param_eq", "ENGINE_NG_RPM", 0 },
            start_state = "coldstart-before-engine-start",
        },
        ["shutdown"] = {
            text = "Engine Shutdown",
            cond = { "param_gt", "ENGINE_NG_RPM", 0 },
            start_state = "shutdown-start",
        }
    },
    states = {
        -- Cold Start
        ["coldstart-before-engine-start"] = {
            text = "Before Engine Start",
            conditions = {
                { text = "Close throttle", cond = { "arg_eq", "THROTTLE_HANDLE1", 0 } },
                { text = "Ignition CB switch to IGN", cond = { "arg_eq", "HLP_IGN", 1 } },
                { text = "FADEC CB switch to FADEC", cond = { "arg_eq", "HLP_FADEC", 1 } },
                { text = "Anti-collision lights to ANTI COLL", cond = { "arg_eq", "HLP_ANTI_COLL", 1 } },
                { text = "Turn ignition key to ON", cond = { "arg_eq", "HLP_MAIN_KEY", 1 } },
                { text = "BATT 1 switch to BATT 1", cond = { "arg_eq", "HLP_BATT1", 1 } },
                { text = "Verify FADEC mode is in AUTO", cond = { "arg_eq", "FADEC_ON_MODE", 0.5 }, highlights = { "HLP_FADEC_BUTTON" } },
                { text = "Wait for CAUTION", cond = { "ind_neq", "Caution", nil }, onlyOnce = true },
                { text = "ACK switch to reset CAUTION", cond = { "ind_eq", "Caution", nil }, highlights = { "HLP_MFK_REC_ACK" },  needAllPrevious = true },
                { text = "Hold MPD TEST switch up", cond = { "arg_eq", "HLP_MPD_TEST", 1 }, onlyOnce = true },
                { text = "BIT/Reset switch UP", cond = { "arg_eq", "HLP_MPD_BIT", 1 }, onlyOnce = true },
                { text = "Wait for BIT test to complete", cond = { "ind_eq", "NGParamDisplay", "ERR", "ind_eq", "LeftParamDisplay", "00" }, onlyOnce = true },
                { text = "BIT/Reset switch DOWN", cond = { "arg_eq", "HLP_MPD_BIT", -1 }, onlyOnce = true },
            },
            next_state = "coldstart-engine-start",
        },
        ["coldstart-engine-start"] = {
            text = "Engine Start",
            conditions = {
                { text = "ACK switch to reset CAUTION", cond = { "ind_eq", "Caution", nil }, highlights = { "HLP_MFK_REC_ACK" } },
                { text = "Set MPD selector to BATTV/STARTV", cond = { "param_gt", "BATTV_STARTV_vis", 0 }, highlights = { "HLP_MPD_SEL" } },
                { text = "Advance trottle to IDLE", cond = { "arg_between", "THROTTLE_HANDLE1", 0.5, 0.6 } },
                { text = "Hold start switch for 2 seconds", cond = { "arg_eq", "HLP_START_SWITCH", 1 }, duration = 2, onlyOnce = true },
                { text = "At 10% Ng: Check battery voltage >= 14V", cond = { "param_gt", "ENGINE_NG_RPM", 0.1, "ind_gt", "LeftParamDisplay", 13 }, onlyOnce = true },
                { text = "At 18% Ng: Check TGT rising", cond = { "param_gt", "ENGINE_NG_RPM", 0.18, "ind_gt", "TGTDisplay", 500 }, onlyOnce = true },
                { text = "At 20% Ng: Check oil pressure rising", cond = { "param_gt", "ENGINE_NG_RPM", 0.20} },
                { text = "At 25% Ng: Check rotor blades turning", cond = { "param_gt", "ENGINE_NG_RPM", 0.25, "param_gt", "BASE_SENSOR_PROPELLER_RPM", 0 } },
                { text = "At 50% Ng: Check start voltage is 0", cond = { "param_gt", "ENGINE_NG_RPM", 0.50, "ind_eq", "RightParamDisplay", "000" } },
                { text = "At 63-65% Ng: Check for Ng stabilized", cond = { "param_between", "ENGINE_NG_RPM", 0.63, 0.65 }, duration = 3 },
            },
            next_state = "coldstart-run-up",
        },
        ["coldstart-run-up"] = {
            text = "Run Up",
            conditions = {
                { text = "DC GEN switch to ON", cond = { "arg_eq", "HLP_DC_GEN", 1 } },
                { text = "AC GEN switch to ON", cond = { "arg_eq", "HLP_AC_GEN", 1 } },
                { text = "ESENTL BUS switch to RUN", cond = { "arg_eq", "HLP_ESSENTIAL_BUS", 1 } },
                { text = "FUEL BOOST switch to ON", cond = { "arg_eq", "HLP_FUELBOOST", 1 } },
                { text = "PART SEP CB push IN", cond = { "arg_eq", "HLP_PART_SEP", 0 } },
                { text = "Advance trottle to OPEN", cond = { "arg_eq", "THROTTLE_HANDLE1", 1.0 } },
                { text = "Set MPD selector to NR/NP", cond = { "param_gt", "NG_NP_vis", 0 }, highlights = { "HLP_MPD_SEL" } },
                { text = "Wait for TGT and RPM to stabilize", cond = { "ind_gt", "LeftParamDisplay", 0.98 }, duration = 3 },
                { text = "Increase NP/NR to 100% using RPM trim", cond = { "ind_eq", "LeftParamDisplay", "100" }, duration = 3, highlights = { "HLP_PILOT_ENG_RPM_TRIM" } },
            },
            next_state = "coldstart-systems",
        },
        ["coldstart-systems"] = {
            text = "Systems",
            conditions = {
                { text = "RADAR DETR switch to ON", cond = { "arg_eq", "HLP_RADAR_DETR", 1 } },
                { text = "RADAR WARN switch to ON", cond = { "arg_eq", "HLP_RADAR_WARN", 1 } },
                { text = "IFF CB switch to ON", cond = { "arg_eq", "HLP_IFF", 1 } },
                { text = "L2MUM switch to ON", cond = { "arg_eq", "HLP_L2MUM", 0 } },
                { text = "CMWS CB switch to ON", cond = { "arg_eq", "HLP_CMWS_SWITCH", 1 } },
                { text = "CMWS PWR to ON", cond = { "arg_eq", "HLP_CI_PWR_KNOB", 0 } },
                -- alq144: { text = "IR JAMMER CB switch to ON", cond = { "arg_eq", "HLP_ALQ144_SWITCH01", 1 } },
                { text = "MMS mode selector to STOW", cond = { "arg_between", "HLP_MMS_MODE_ROTATOR", 0.19, 0.21 } },
                { text = "SCAS power switch to PWR", cond = { "arg_eq", "HLP_SCAS_POWER_SWITCH", 1 } },
                { text = "MASTER switch to STBY", cond = { "arg_eq", "HLP_ACP_MASTER_SWITCH", 0 } },
            },
            next_state = "coldstart-before-takeoff",
        },
        ["coldstart-before-takeoff"] = {
            text = "Before Take-Off",
            conditions = {
                { text = "SCAS PITCH/ROLL/YAW to ON", cond = { "arg_eq", "HLP_SCAS_PITCHROLL_SWITCH", 1, "arg_eq", "HLP_SCAS_YAW_SWITCH", 1 } },
                { text = "Set MPD selector to FUEL QTY", cond = { "param_gt", "FUELQTY_ENGTRQ_vis", 0 }, highlights = { "HLP_MPD_SEL" } },
                { text = "CMWS ARM switch to ARM", cond = { "arg_eq", "HLP_CMWS_ARM_SAFE", 1 } },
                -- alq144: { text = "Set IR JAMMER switch to XMTR", cond = { "arg_eq", "HLP_ALQ144_top_front_01", 1 } },
                { text = "Set MPD to VSD", cond = { "ind_neq", "B1_TEXT", "VSD" }, highlights = { "HLP_RMFD_B1" } }
            },
            next_state = "coldstart-complete",
        },
        ["coldstart-complete"] = {
            text = "Cold start complete",
        },

        -- Engine Shutdown
        ["shutdown-start"] = {
            text = "Engine Shutdown",
            conditions = {
                { text = "Flight controls: Cyclic centered", cond = { "arg_between", "PILOT_CYCLIC_PITCH", -0.05, 0.05, "arg_between", "PILOT_CYCLIC_ROLL", -0.05, 0.05 } },
                { text = "Flight controls: Pedals neutral", cond = { "param_between", "PEDAL", -0.05, 0.05  } },
                { text = "Flight controls: Collective down", cond = { "arg_lt", "PILOT_COLLECTIVE", 0.05 } },
                { text = "FORCE TRIM switch to FORCE TRIM", cond = { "arg_eq", "HLP_SCAS_FORCETRIM_SWITCH", 1 } },
                { text = "Reduce throttle to IDLE", cond = { "arg_lt", "THROTTLE_HANDLE1", 0.6 } },
                { text = "SCAS power switch to OFF", cond = { "arg_eq", "HLP_SCAS_POWER_SWITCH", 0 } },
                { text = "SCAS PITCH/ROLL/YAW to OFF", cond = { "arg_eq", "HLP_SCAS_PITCHROLL_SWITCH", 0, "arg_eq", "HLP_SCAS_YAW_SWITCH", 0 } },
                { text = "MASTER switch to OFF", cond = { "arg_eq", "HLP_ACP_MASTER_SWITCH", -1 } },
                { text = "GUN switch to SAFE", cond = { "arg_eq", "HLP_ACP_GUN_SWITCH", -1 } },
                { text = "CMWS ARM switch to SAFE", cond = { "arg_eq", "HLP_CMWS_ARM_SAFE", 0 } },
                { text = "MMS mode selector to OFF", cond = { "arg_eq", "HLP_MMS_MODE_ROTATOR", 0 } },
                { text = "CMWS PWR to OFF", cond = { "arg_eq", "HLP_CI_PWR_KNOB", -1 } },
            },
            next_state = "shutdown-close-throttle",
        },
        ["shutdown-close-throttle"] = {
            text = "Engine Shutdown",
            conditions = {
                { text = "Close throttle", cond = { "arg_eq", "THROTTLE_HANDLE1", 0 } },
                { text = "DC GEN switch to OFF", cond = { "arg_eq", "HLP_DC_GEN", 0 } },
                { text = "AC GEN switch to OFF", cond = { "arg_eq", "HLP_AC_GEN", 0 } },
                { text = "ENG OIL BYPASS switch to OFF", cond = { "arg_eq", "HLP_ENGOIL_BYPASS", 0 } },
                { text = "ENG ANTI ICE switch to OFF", cond = { "arg_eq", "HLP_ENG_ANTI_ICE", 0 } },
                { text = "FUEL BOOST switch to OFF", cond = { "arg_eq", "HLP_FUELBOOST", 0 } },
                { text = "COMPT BLWR switch to AUTO", cond = { "arg_eq", "HLP_COMPT_BLWR", -1 } },
                { text = "LDEFOG and RDEFOG switches to OFF", cond = { "arg_eq", "HLP_LDEFOG", 0, "arg_eq", "HLP_RDEFOG", 0 } },
                { text = "HTR and PITOT HTR switches to OFF", cond = { "arg_eq", "HLP_HTR", 0, "arg_eq", "HLP_PITOTHTR", 0 } },
                { text = "Below 10% Ng: ESENTL BUS switch to START", cond = { "param_lt", "ENGINE_NG_RPM", 0.1, "arg_eq", "HLP_ESSENTIAL_BUS", 0 },  },
            },
            next_state = "shutdown-power-off",
        },
        ["shutdown-power-off"] = {
            text = "Power Off",
            conditions = {
                { text = "Wait until rotor stopped", cond = { "param_eq", "BASE_SENSOR_PROPELLER_RPM", 0 } },
                { text = "BATT 1 switch to OFF", cond = { "arg_eq", "HLP_BATT1", 0 } },
                { text = "PART SEP CB pull OUT", cond = { "arg_eq", "HLP_PART_SEP", 1 } },
                { text = "RADAR DETR switch to OFF", cond = { "arg_eq", "HLP_RADAR_DETR", 0 } },
                { text = "RADAR WARN switch to OFF", cond = { "arg_eq", "HLP_RADAR_WARN", 0 } },
                { text = "IFF CB switch to OFF", cond = { "arg_eq", "HLP_IFF", 0 } },
                { text = "L2MUM switch to OFF", cond = { "arg_eq", "HLP_L2MUM", 1 } },
                { text = "CMWS CB switch to OFF", cond = { "arg_eq", "HLP_CMWS_SWITCH", 0 } },
                -- alq144: { text = "IR JAMMER CB switch to OFF", cond = { "arg_eq", "HLP_ALQ144_SWITCH01", 0 } },
                { text = "Anti-collision lights to OFF", cond = { "arg_eq", "HLP_ANTI_COLL", 0 }},
                { text = "Position lights to OFF", cond = { "arg_eq", "HLP_POSITION_LIGHT", -1 }},
                { text = "Flood lights to OFF", cond = { "arg_eq", "HLP_FLOOD_LT_SW", -1 }},
                { text = "Ignition CB switch to OFF", cond = { "arg_eq", "HLP_IGN", 0 } },
                { text = "FADEC CB switch to OFF", cond = { "arg_eq", "HLP_FADEC", 0 } },
                { text = "Turn ignition key to OFF", cond = { "arg_eq", "HLP_MAIN_KEY", 0 } },
            },
            next_state = "shutdown-complete",
        },
        ["shutdown-complete"] = {
            text = "Shutdown complete",
            conditions = {},
        },
    },
    args = {
        PILOT_CYCLIC_PITCH = 1,
        PILOT_CYCLIC_ROLL = 2,
        PILOT_COLLECTIVE = 3,
        HLP_START_SWITCH = 7,
        THROTTLE_HANDLE1 = 8,
        HLP_IDLE_REL_BUTTON = 9,
        HLP_PILOT_ENG_RPM_TRIM = 15,
        HLP_PILOT_STICK_TRIMREL_BUTTON = 27,
        HLP_CI_PWR_KNOB = 38,
        HLP_CI_AUDIO_KNOB = 39,
        HLP_CI_LAMP_KNOB = 40,
        HLP_CMWS_ARM_SAFE = 44,
        HLP_CMWS_AUTO_BYPASS = 45,
        HLP_MAIN_KEY = 50,
        Attitude_W = 54,
        Attitude_Pitch = 55,
        Attitude_Roll = 56,
        HLP_RMFD_B1 = 83,
        HLP_RMFD_B2 = 84,
        HLP_RMFD_B3 = 85,
        HLP_RMFD_B4 = 86,
        HLP_MPD_BIT = 118,
        HLP_MPD_TEST = 119,
        HLP_MPD_SEL = 120,
        HLP_MPD_BKUP = 121,
        HLP_PITOT_HTR = 146,
        HLP_MMS_MODE_ROTATOR = 147,
        HLP_SCAS_FORCETRIM_SWITCH = 161,
        HLP_SCAS_HYDSYS_SWITCH = 162,
        HLP_SCAS_PITCHROLL_SWITCH = 163,
        HLP_SCAS_YAW_SWITCH = 164,
        HLP_SCAS_POWER_SWITCH = 165,
        HLP_SCAS_TEST_BUTTON = 166,
        HLP_ACP_MASTER_SWITCH = 171,
        HLP_ACP_GUN_SWITCH = 172,
        HLP_MFK_REC_ACK = 192,
        HLP_FADEC = 247,
        HLP_BATT1 = 248,
        HLP_IGN = 250,
        HLP_PITOTHTR = 254,
        HLP_HTR = 255,
        HLP_LDEFOG = 256,
        HLP_RDEFOG = 257,
        HLP_COMPT_BLWR = 258,
        HLP_FUELBOOST = 259,
        HLP_ENG_ANTI_ICE = 260,
        HLP_ENGOIL_BYPASS = 261,
        HLP_ESSENTIAL_BUS = 262,
        HLP_AC_GEN = 263,
        HLP_DC_GEN = 264,
        HLP_BFT = 268,
        HLP_IFF = 269,
        HLP_RADAR_DETR = 270,
        HLP_RADAR_WARN = 271,
        HLP_L2MUM = 272,
        HLP_PART_SEP = 273,
        HLP_ir_beacon_on_off = 274,
        HLP_FORMATION_ROTATOR = 275,
        HLP_CMWS_SWITCH = 276,
        HLP_FLOOD_LT_SW = 279,
        HLP_POSITION_LIGHT = 280,
        HLP_ANTI_COLL = 281,
        HLP_FADEC_BUTTON = 282,
        FADEC_ON_MODE = 283,
        HLP_PDU_bit = 310,
        HLP_ALQ144_SWITCH01 = 841,
        HLP_ALQ144_top_front_01 = 842,
    },
    params = {
        "NG_NP_vis",
        "FUELQTY_ENGTRQ_vis",
        "ACV_RECTV_vis",
        "RECTLD_SGENLD_vis",
        "BATTV_STARTV_vis",
        "BIT_vis",
        "LT_vis",
        "MPD_vis",
        "SW_vis",
        "UTC_vis",
        "ENGINE_NG_RPM",
        "IS_LANDED",
        "BASE_SENSOR_PROPELLER_RPM",
        "BASE_SENSOR_RADALT",
        "BASE_SENSOR_CANOPY_POS",
        "BASE_SENSOR_CANOPY_STATE",
        "PEDAL",
        "PEDAL_TRIM",
        "PITCH_TRIM",
        "ROLL_TRIM",
        "SlipBall",
    },
    indications = {
        [1] = {
            "NGParamDisplay",
            "LeftParamDisplay",
            "RightParamDisplay",
        },
        [2] = {
            "TGTDisplay",
            "TRQDisplay",
        },
        [3] = {
            "Caution",
            "B1_TEXT",
            "B2_TEXT",
            "B3_TEXT",
            "B4_TEXT",
            "MMS_ADVISORY_TEXT",
        }
    },
    commands = {},
}
